### ISSUE TITLE
what is meant by the readme statement: "the script will auto-update itself"?

### ISSUE THREAD

**Issue by grenade** [asifbacchus/CloudflareDDNS#1]
reading the script, i didn't find evidence that the script downloads updates for itself and that is some relief since there's no way i'd want to regularly execute code from a script that can modify itself at a later date to run arbitrary commands on my system.

please can you explain what this [statement](https://github.com/asifbacchus/CloudflareDDNS/blob/fddb406/README.md?plain=1#L59) means?

**Comment by asifbacchus** [comment]
Just means that you can rename the script to anything you'd like and it will use that same name when generating log files, etc. Take this code for example:

```sh
scriptName="$(basename "$0")"
logFile="$scriptPath/${scriptName%.*}.log"
```

Here the script reads its own filename (even if you choose to rename it) and then uses that name for the log file. This type of internal "auto-updating" reference also is used in the embedded help text which will update the sample command lines to use the actual name of the script instead of the default name.

Perhaps I should re-word that in the readme to be less confusing... maybe do a long-overdue update on this entire script :-P

I hope this answers your question/alleviates your concerns? If not, let me know and I'll try to explain better.
